[application]

[web.app]

# Served from https://jprellberg.github.io/adventure-tools/ on GitHub Pages
base_path = "adventure-tools"

# HTML title tag content
title = "adventure-tools"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
